INSERT INTO Data (ID, Name, Age) VALUES (-- , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (1. , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Create , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (the , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (table , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (structure, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (TABLE , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (electronic_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ((, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year_month , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (VARCHAR(7), '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (two_week_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INT, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (three_week_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INT, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (four_week_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INT, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (bus_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INT, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INT, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ();, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (-- , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Note: , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (You , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (would , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (need , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (to , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (import , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (the , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CSV , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (data , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (into , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (this , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (table , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (using , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (your , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (database's , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (import , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (tools, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (-- , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2. , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Basic , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (analysis , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (queries, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (-- , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Monthly , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (overview, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year_month, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_sales, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ROUND(total_sales / , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ((SELECT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AVG(total_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (electronic_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (* , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (100, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (percent_of_avg, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (electronic_sales, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ORDER , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (BY , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUBSTR(year_month, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (4, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2), ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (-- , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Month, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUBSTR(year_month, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (1, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2); , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (-- , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Year, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (-- , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Yearly , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (summary, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUBSTR(year_month, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (4, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUM(total_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (yearly_total, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ROUND(AVG(total_sales), ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (monthly_avg, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (MAX(total_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (peak_month, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (MIN(total_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (lowest_month, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (electronic_sales, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (GROUP , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (BY , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ORDER , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (BY , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year;, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (-- , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (3. , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (trend , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (analysis , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (by , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (product , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (category, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUBSTR(year_month, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (4, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUM(two_week_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_2w, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUM(three_week_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_3w, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUM(four_week_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_4w, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUM(bus_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_bus, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUM(two_week_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (+ , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (three_week_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (+ , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (four_week_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (+ , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (bus_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (calculated_total, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUM(total_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (reported_total, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (electronic_sales, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (GROUP , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (BY , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ORDER , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (BY , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year;, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (-- , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (4. , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Monthly , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (growth , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (analysis, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (WITH , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (monthly_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ((, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year_month, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_sales, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (LAG(total_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (OVER , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ((ORDER , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (BY , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUBSTR(year_month, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (4, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2), ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUBSTR(year_month, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (1, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2)) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (prev_month_sales, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (electronic_sales, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year_month, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_sales, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (prev_month_sales, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ROUND((total_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (- , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (prev_month_sales) / , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (prev_month_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (* , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (100, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (monthly_growth_percent, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (monthly_sales, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (WHERE , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (prev_month_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (IS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (NOT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (NULL, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ORDER , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (BY , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUBSTR(year_month, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (4, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2), ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUBSTR(year_month, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (1, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2);, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (-- , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (5. , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Seasonal , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (analysis , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ((compare , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (same , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (months , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (across , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (years), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUBSTR(year_month, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (1, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (month, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUBSTR(year_month, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (4, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year_17, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ((SELECT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (electronic_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (WHERE , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year_month , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (= , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CONCAT('Apr-', ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year_17)) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (apr_sales, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ((SELECT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (electronic_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (WHERE , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year_month , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (= , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CONCAT('May-', ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year_17)) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (may_sales, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ((SELECT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (electronic_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (WHERE , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year_month , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (= , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CONCAT('Dec-', ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year_17)) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (dec_sales, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ((SELECT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (DISTINCT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUBSTR(year_month, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (4, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year_17 , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (electronic_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (years, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (WHERE , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year_17 , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (IN , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (('17', ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ('18', ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ('19', ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ('20', ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ('21', ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ('22', ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ('23'), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ORDER , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (BY , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year_17;, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (-- , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (6. , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Create , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (a , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (view , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (for , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (category , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (performance, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (VIEW , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (category_performance , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUBSTR(year_month, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (4, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ('2 , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Week' , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (category, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUM(two_week_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_sales, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ROUND(SUM(two_week_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (* , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (100.0 / , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUM(total_sales), ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (percent_of_total, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (electronic_sales, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (GROUP , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (BY , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (UNION , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ALL, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUBSTR(year_month, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (4, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ('3 , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Week' , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (category, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUM(three_week_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_sales, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ROUND(SUM(three_week_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (* , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (100.0 / , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUM(total_sales), ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (percent_of_total, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (electronic_sales, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (GROUP , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (BY , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (UNION , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ALL, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUBSTR(year_month, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (4, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ('4 , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Week' , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (category, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUM(four_week_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_sales, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ROUND(SUM(four_week_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (* , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (100.0 / , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUM(total_sales), ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (percent_of_total, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (electronic_sales, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (GROUP , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (BY , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (UNION , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ALL, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUBSTR(year_month, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (4, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ('BUS' , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (category, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUM(bus_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_sales, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ROUND(SUM(bus_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (* , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (100.0 / , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SUM(total_sales), ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (percent_of_total, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (electronic_sales, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (GROUP , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (BY , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year;, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (-- , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (7. , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Query , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (the , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (view , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (to , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (see , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (category , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (trends, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (* , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (category_performance, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ORDER , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (BY , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (category;, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (-- , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (8. , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Identify , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (best , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (and , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (worst , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (performing , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (months, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ((SELECT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year_month, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_sales, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ('Top' , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (performance, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (electronic_sales, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ORDER , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (BY , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (DESC, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (LIMIT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (5), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (UNION , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ALL, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ((SELECT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (year_month, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_sales, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ('Bottom' , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (performance, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (electronic_sales, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (WHERE , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (> , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (0, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ORDER , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (BY , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ASC, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (LIMIT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (5), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ORDER , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (BY , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (performance, ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (total_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (DESC;, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (-- , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (9. , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Create , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (an , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (index , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (to , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (optimize , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (date-, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (based , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (queries, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (CREATE , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (INDEX , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (idx_year_month , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ON , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (electronic_sales(year_month);, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (-- , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (10. , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (Complex , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (query , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (with , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (subquery , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (- , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (find , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (months , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (where , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2-, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (week , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (were , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (above , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (average, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (SELECT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (e.year_month, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (e.two_week_sales, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ((SELECT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ROUND(AVG(two_week_sales), ' ', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (2) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (electronic_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (avg_2w_sales, '', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (  , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (e.two_week_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (- , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ((SELECT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AVG(two_week_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (electronic_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AS , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (difference, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (electronic_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (e, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (WHERE , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (e.two_week_sales , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (> , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ((SELECT , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (AVG(two_week_sales) , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (FROM , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (electronic_sales), 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES ( , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (, 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (ORDER , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (BY , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (difference , 'undefined', undefined);
INSERT INTO Data (ID, Name, Age) VALUES (DESC;, 'undefined', undefined);